language: elixir

sudo: false

elixir:
  - 1.0.0
  - 1.1.1
  - mix

otp_release:
  - 17.4
  - 18.0

script:
  - MIX_ENV=docs mix do deps.get, inch.report
  - MIX_ENV=test mix do deps.get, compile, coveralls.travis
